use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use unigetui_policy_simulator_core::{
    BrokerEnvelope, BrokerEvaluationResponse, CommandLineBuilder, DocumentLoader,
    EnvelopeMetadata, PackageRequest, PolicyDocument, PolicyError, PolicyEvaluator,
    Result,
};

const TEST_PROTOCOL_VERSION: &str = "1.0";
const TEST_BROKER_NAME: &str = "UniGetUI Rust policy simulator tests";
const TEST_TRANSPORT: &str = "http-loopback-simulator";
const GENERATED_ALLOW_NOTE: &str = "Generated by the Rust parity runner for schema validation only.";
const GENERATED_VALIDATION_NOTE: &str = "Generated validation failure by the Rust parity runner for schema validation only.";
const FIXED_TIMESTAMP: &str = "2026-05-22T00:00:00Z";

pub fn run_with_policy_root(policy_root: &Path) -> Result<()> {
    let samples_root = policy_root.join("samples");
    let policy_schema_path = policy_root.join("schemas").join("unigetui.package-policy.schema.1.0.json");
    let request_schema_path = policy_root.join("schemas").join("unigetui.package-request.schema.1.0.json");
    let response_schema_path = policy_root.join("schemas").join("unigetui.package-broker-response.schema.1.0.json");
    let scenario_root = samples_root.join("scenarios");
    let response_root = samples_root.join("responses");
    let loader = DocumentLoader;
    let evaluator = PolicyEvaluator;

    let mut failures = Vec::new();
    let mut passed = 0usize;

    let mut manifest_paths = fs::read_dir(&scenario_root)
        .map_err(io_validation_error(&scenario_root, "scenario directory"))?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| {
            path.extension().and_then(|value| value.to_str()) == Some("json")
                && path
                    .file_name()
                    .and_then(|value| value.to_str())
                    .is_some_and(|value| value.ends_with(".scenarios.json"))
        })
        .collect::<Vec<_>>();
    manifest_paths.sort();

    for manifest_path in manifest_paths {
        let manifest_text = fs::read_to_string(&manifest_path)
            .map_err(io_validation_error(&manifest_path, "scenario manifest"))?;
        let manifest: ScenarioManifest = serde_json::from_str(&manifest_text).map_err(|error| {
            PolicyError::validation(format!(
                "Failed to parse scenario manifest '{}': {}",
                manifest_path.display(),
                error
            ))
        })?;

        for scenario in manifest.scenarios {
            let policy_path = samples_root.join(&scenario.policy);
            let request_path = samples_root.join(&scenario.request);
            let response = evaluate_scenario(&loader, &evaluator, &policy_path, &request_path, &policy_schema_path, &request_schema_path);
            let decision_passed = response.decision == scenario.expected_decision;
            let rule_passed = scenario
                .expected_rule_id
                .as_deref()
                .is_none_or(|expected_rule_id| response.rule_id == expected_rule_id);
            if decision_passed && rule_passed {
                passed += 1;
            } else {
                failures.push(format!(
                    "{}: expected {}/{}, got {}/{}. Reason: {}",
                    scenario.id,
                    scenario.expected_decision,
                    scenario.expected_rule_id.as_deref().unwrap_or(""),
                    response.decision,
                    response.rule_id,
                    response.reason
                ));
            }
        }
    }

    let (command_checks_passed, command_checks_total, command_failures) =
        run_command_checks(&loader, &samples_root, &request_schema_path);
    failures.extend(command_failures);

    let (response_samples_passed, response_samples_total, response_sample_failures) =
        run_response_sample_checks(&loader, &response_root, &response_schema_path);
    failures.extend(response_sample_failures);

    let (generated_responses_passed, generated_responses_total, generated_response_failures) =
        run_generated_response_checks(
            &loader,
            &samples_root,
            &policy_schema_path,
            &request_schema_path,
            &response_schema_path,
        );
    failures.extend(generated_response_failures);

    for failure in &failures {
        eprintln!("{failure}");
    }

    println!("Scenario checks passed: {passed}");
    println!("Command construction checks passed: {command_checks_passed} of {command_checks_total}");
    println!("Response sample schema checks passed: {response_samples_passed} of {response_samples_total}");
    println!("Generated response schema checks passed: {generated_responses_passed} of {generated_responses_total}");

    if failures.is_empty() {
        Ok(())
    } else {
        Err(PolicyError::validation(format!(
            "{} Rust parity check(s) failed.",
            failures.len()
        )))
    }
}

fn evaluate_scenario(
    loader: &DocumentLoader,
    evaluator: &PolicyEvaluator,
    policy_path: &Path,
    request_path: &Path,
    policy_schema_path: &Path,
    request_schema_path: &Path,
) -> BrokerEvaluationResponse {
    match (
        loader.load_file::<PolicyDocument>(policy_path, Some(policy_schema_path)),
        loader.load_file::<PackageRequest>(request_path, Some(request_schema_path)),
    ) {
        (Ok(policy), Ok(request)) => match evaluator.evaluate(&policy.value, &request.value) {
            Ok(decision) => {
                let command = if decision.decision == "allow" {
                    CommandLineBuilder::build(&request.value).unwrap_or_default()
                } else {
                    Vec::new()
                };
                BrokerEvaluationResponse {
                    request_id: request.value.request_id.clone(),
                    manager: Some(request.value.manager.name.clone()),
                    source: Some(request.value.source.name.clone()),
                    package_id: Some(request.value.package.id.clone()),
                    operation: Some(request.value.operation.clone()),
                    decision: decision.decision,
                    rule_id: decision.rule_id,
                    reason: decision.reason,
                    would_execute: !command.is_empty(),
                    command,
                    mode: Some("simulated-elevated".to_string()),
                }
            }
            Err(error) => validation_failure_response(error),
        },
        (Err(error), _) | (_, Err(error)) => validation_failure_response(error),
    }
}

fn run_command_checks(
    loader: &DocumentLoader,
    samples_root: &Path,
    request_schema_path: &Path,
) -> (usize, usize, Vec<String>) {
    let checks = vec![
        CommandCheck::new(
            "WinGet install",
            samples_root.join("requests").join("winget-vscode-install.request.json"),
            vec!["winget.exe", "install", "--id", "Microsoft.VisualStudioCode", "--exact", "--source", "winget", "--scope", "machine", "--silent", "--architecture", "x64"],
        ),
        CommandCheck::new(
            "WinGet update maps to upgrade",
            samples_root.join("requests").join("winget-vscode-update-in-range.request.json"),
            vec!["winget.exe", "upgrade", "--id", "Microsoft.VisualStudioCode", "--exact", "--source", "winget", "--scope", "machine", "--version", "1.96.0", "--silent", "--architecture", "x64"],
        ),
        CommandCheck::new(
            "WinGet uninstall",
            samples_root.join("requests").join("winget-git-uninstall.request.json"),
            vec!["winget.exe", "uninstall", "--id", "Git.Git", "--exact", "--source", "winget", "--scope", "machine", "--silent", "--architecture", "x64"],
        ),
        CommandCheck::new(
            "PowerShell install",
            samples_root.join("requests").join("powershell-pester-currentuser.request.json"),
            vec!["pwsh.exe", "-NoProfile", "-Command", "Install-Module", "-Name", "Pester", "-Scope", "CurrentUser"],
        ),
        CommandCheck::new(
            "PowerShell versioned install",
            samples_root.join("requests").join("powershell-pester-version-allowed.request.json"),
            vec!["pwsh.exe", "-NoProfile", "-Command", "Install-Module", "-Name", "Pester", "-Scope", "CurrentUser", "-RequiredVersion", "5.5.0"],
        ),
        CommandCheck::new(
            "PowerShell update",
            samples_root.join("requests").join("powershell-pester-update-currentuser.request.json"),
            vec!["pwsh.exe", "-NoProfile", "-Command", "Update-Module", "-Name", "Pester", "-RequiredVersion", "5.5.0"],
        ),
    ];

    let total = checks.len();
    let mut passed = 0usize;
    let mut failures = Vec::new();

    for check in checks {
        match loader.load_file::<PackageRequest>(&check.request_path, Some(request_schema_path)) {
            Ok(request) => match CommandLineBuilder::build(&request.value) {
                Ok(command) if command == check.expected_command => passed += 1,
                Ok(command) => failures.push(format!(
                    "{} command mismatch: {}",
                    check.name,
                    command.join(" ")
                )),
                Err(error) => failures.push(format!("{} failed to build command: {}", check.name, error)),
            },
            Err(error) => failures.push(format!("{} failed to load request: {}", check.name, error)),
        }
    }

    (passed, total, failures)
}

fn run_response_sample_checks(
    loader: &DocumentLoader,
    response_root: &Path,
    response_schema_path: &Path,
) -> (usize, usize, Vec<String>) {
    let mut response_paths = match fs::read_dir(response_root) {
        Ok(entries) => entries
            .filter_map(|entry| entry.ok().map(|entry| entry.path()))
            .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("json"))
            .collect::<Vec<_>>(),
        Err(error) => {
            return (
                0,
                0,
                vec![format!("response sample directory failed to load: {}", error)],
            )
        }
    };
    response_paths.sort();

    let total = response_paths.len();
    let mut passed = 0usize;
    let mut failures = Vec::new();

    for response_path in response_paths {
        match loader.load_file::<BrokerEnvelope>(&response_path, Some(response_schema_path)) {
            Ok(_) => passed += 1,
            Err(error) => {
                let file_name = response_path.file_name().and_then(|value| value.to_str()).unwrap_or("<unknown>");
                failures.push(format!("response sample {} failed schema validation: {}", file_name, error));
            }
        }
    }

    (passed, total, failures)
}

fn run_generated_response_checks(
    loader: &DocumentLoader,
    samples_root: &Path,
    policy_schema_path: &Path,
    request_schema_path: &Path,
    response_schema_path: &Path,
) -> (usize, usize, Vec<String>) {
    let mut failures = Vec::new();
    let policy_path = samples_root.join("corporate-allowlist.policy.json");
    let allow_request_path = samples_root.join("requests").join("winget-vscode-install.request.json");
    let deny_request_path = samples_root.join("requests").join("winget-unknown-install.request.json");

    let policy = match loader.load_file::<PolicyDocument>(&policy_path, Some(policy_schema_path)) {
        Ok(document) => document.value,
        Err(error) => {
            failures.push(format!("generated response setup failed to load policy: {}", error));
            return (0, 3, failures);
        }
    };
    let allow_request = match loader.load_file::<PackageRequest>(&allow_request_path, Some(request_schema_path)) {
        Ok(document) => document.value,
        Err(error) => {
            failures.push(format!("generated response setup failed to load allow request: {}", error));
            return (0, 3, failures);
        }
    };
    let deny_request = match loader.load_file::<PackageRequest>(&deny_request_path, Some(request_schema_path)) {
        Ok(document) => document.value,
        Err(error) => {
            failures.push(format!("generated response setup failed to load deny request: {}", error));
            return (0, 3, failures);
        }
    };

    let metadata = EnvelopeMetadata {
        broker_name: TEST_BROKER_NAME.to_string(),
        protocol_version: TEST_PROTOCOL_VERSION.to_string(),
        transport: TEST_TRANSPORT.to_string(),
        pipe_name: None,
        elevated_simulation: true,
    };

    let mut passed = 0usize;
    let total = 3usize;

    let allow_envelope = match build_generated_allow_envelope(&policy, &allow_request, &metadata) {
        Ok(envelope) => envelope,
        Err(error) => {
            failures.push(format!("generated response allow failed to build: {}", error));
            return (passed, total, failures);
        }
    };
    if let Some(error) = validate_generated_response(loader, response_schema_path, "generated response allow", &allow_envelope) {
        failures.push(error);
    } else {
        passed += 1;
    }

    let deny_envelope = match build_generated_deny_envelope(&policy, &deny_request, &metadata) {
        Ok(envelope) => envelope,
        Err(error) => {
            failures.push(format!("generated response deny failed to build: {}", error));
            return (passed, total, failures);
        }
    };
    if let Some(error) = validate_generated_response(loader, response_schema_path, "generated response deny", &deny_envelope) {
        failures.push(error);
    } else {
        passed += 1;
    }

    let validation_envelope = BrokerEnvelope::validation_failure(
        &policy,
        "audit-generated-validation-failure",
        "Synthetic validation failure for schema coverage.",
        &metadata,
        GENERATED_VALIDATION_NOTE,
        FIXED_TIMESTAMP,
    );
    if let Some(error) = validate_generated_response(
        loader,
        response_schema_path,
        "generated response validation failure",
        &validation_envelope,
    ) {
        failures.push(error);
    } else {
        passed += 1;
    }

    (passed, total, failures)
}

fn build_generated_allow_envelope(
    policy: &PolicyDocument,
    request: &PackageRequest,
    metadata: &EnvelopeMetadata,
) -> std::result::Result<BrokerEnvelope, PolicyError> {
    let evaluator = PolicyEvaluator;
    let decision = evaluator.evaluate(policy, request)?;
    let command = CommandLineBuilder::build(request)?;
    let response = BrokerEvaluationResponse {
        request_id: request.request_id.clone(),
        manager: Some(request.manager.name.clone()),
        source: Some(request.source.name.clone()),
        package_id: Some(request.package.id.clone()),
        operation: Some(request.operation.clone()),
        decision: decision.decision,
        rule_id: decision.rule_id,
        reason: decision.reason,
        would_execute: true,
        command,
        mode: Some("simulated-elevated".to_string()),
    };

    Ok(BrokerEnvelope::from_evaluation(
        policy,
        "audit-generated-allow",
        &response,
        metadata,
        GENERATED_ALLOW_NOTE,
        FIXED_TIMESTAMP,
    ))
}

fn build_generated_deny_envelope(
    policy: &PolicyDocument,
    request: &PackageRequest,
    metadata: &EnvelopeMetadata,
) -> std::result::Result<BrokerEnvelope, PolicyError> {
    let evaluator = PolicyEvaluator;
    let decision = evaluator.evaluate(policy, request)?;
    let response = BrokerEvaluationResponse {
        request_id: request.request_id.clone(),
        manager: Some(request.manager.name.clone()),
        source: Some(request.source.name.clone()),
        package_id: Some(request.package.id.clone()),
        operation: Some(request.operation.clone()),
        decision: decision.decision,
        rule_id: decision.rule_id,
        reason: decision.reason,
        would_execute: false,
        command: Vec::new(),
        mode: Some("simulated-elevated".to_string()),
    };

    Ok(BrokerEnvelope::from_evaluation(
        policy,
        "audit-generated-deny",
        &response,
        metadata,
        GENERATED_ALLOW_NOTE,
        FIXED_TIMESTAMP,
    ))
}

fn validate_generated_response(
    loader: &DocumentLoader,
    response_schema_path: &Path,
    document_name: &str,
    envelope: &BrokerEnvelope,
) -> Option<String> {
    let text = match serde_json::to_string(envelope) {
        Ok(text) => text,
        Err(error) => return Some(format!("{} failed serialization: {}", document_name, error)),
    };

    match loader.load_text::<BrokerEnvelope>(&text, document_name, "json", Some(response_schema_path)) {
        Ok(_) => None,
        Err(error) => Some(format!("{} failed schema validation: {}", document_name, error)),
    }
}

fn validation_failure_response(error: PolicyError) -> BrokerEvaluationResponse {
    BrokerEvaluationResponse {
        request_id: "<validation-failure>".to_string(),
        manager: None,
        source: None,
        package_id: None,
        operation: None,
        decision: "deny".to_string(),
        rule_id: "<validation-failure>".to_string(),
        reason: error.to_string(),
        would_execute: false,
        command: Vec::new(),
        mode: Some("simulated-elevated".to_string()),
    }
}

fn io_validation_error<'a>(path: &'a Path, kind: &'static str) -> impl FnOnce(std::io::Error) -> PolicyError + 'a {
    move |error| PolicyError::validation(format!("Failed to read {} '{}': {}", kind, path.display(), error))
}

#[derive(Debug, Deserialize)]
struct ScenarioManifest {
    scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    id: String,
    policy: String,
    request: String,
    #[serde(rename = "expectedDecision")]
    expected_decision: String,
    #[serde(rename = "expectedRuleId")]
    expected_rule_id: Option<String>,
}

struct CommandCheck {
    name: &'static str,
    request_path: PathBuf,
    expected_command: Vec<String>,
}

impl CommandCheck {
    fn new(name: &'static str, request_path: PathBuf, expected_command: Vec<&'static str>) -> Self {
        Self {
            name,
            request_path,
            expected_command: expected_command.into_iter().map(str::to_string).collect(),
        }
    }
}